PREFIX : <http://semantics.id/ns/example/movie#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
DESCRIBE ?movie
WHERE { ?movie rdf:type :Movie ;
			   :hasActor ?actress .
		?actress :hasName "Emma Watson" . }