PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://semantics.id/ns/example/movie#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
CONSTRUCT { ?movie :writtenAndDirectedBy ?writers_name . }
WHERE { ?movie rdf:type :Movie ;
			   rdfs:label ?title ;
			   :hasWriter ?writer ;
			   :hasMovieDirector ?director .
		?writer :hasName ?writers_name .
	FILTER (?writer = ?director)
}